### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by chucheria** [rladies/blog#27]
Before start to think about this I would like to know in which point we are. Last thing I know was that the blog should be in English because it was a global blog, we can link other blogs here (from other chapters) or even give a subdomain like: paris.rladies.org (although that can be tricky because some chapters have website and blog). And anyway, this is kind of limited to blog post different from the translations of the central blog.

From my point of view, I think we could link chapters blogs/websites but not translate the central blog, I know it can be seen as not including but the translations can be done in other blogs and just link the original (like Rbloggers do at the end of posts).

What do you think? @maelle @ledell @gdequeiroz @hfrick @cvitolo

**Comment by cvitolo** [comment]
I agree with you! Let's just link to other blogs, not create subdomains
that could end up being difficult to manage.

Regarding the translation, we can leave it in English for the time being.

**Comment by chucheria** [comment]
Awesome! thanks @cvitolo. I'm going to work in a module to link other pages then (easier than the multilanguage 😬 )

**Comment by Athanasiamo** [comment]
I implemented multilanguage site when we changed the theme and workflow. We had the discussion in slack about this. As a first step towards also merging the blog with the new website when ready.
